### ISSUE TITLE
Use generics for Multipage guis to make it easier to use subclasses of Gui as pages

### ISSUE THREAD

**Issue by dev-null-undefined** [the-codeboy/BukkitBootstrap#8]

**Comment by the-codeboy** [comment]
This might not be needed anymore. So far, I've only ever used subclasses to achieve what was implemented in #10. Maybe we'll come back to this to add things like dragging menu items but at the moment I think that's not such an important feature. Plus when we do need it we can just implement it in the normal gui class so there shouldn't be any subclasses needed. Even if there is ever a reason to use subclasses this already isn't that hard to do even without changes to Gui
